//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 10:51:07 PM CST 
//


package com.redfin.foodtruck.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rows">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="row" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dayorder" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="dayofweekstr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="starttime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="endtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="permit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="locationdesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="optionaltext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="locationid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="start24" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="end24" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cnn" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="addr_date_create" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="addr_date_modified" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                             &lt;element name="lot" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="coldtruck" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="applicant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                             &lt;element name="location_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="location_2_address" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="location_2_city" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="location_2_state" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="location_2_zip" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="_uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="_position" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                           &lt;attribute name="_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rows"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(required = true)
    protected Response.Rows rows;

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Rows }
     *     
     */
    public Response.Rows getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Rows }
     *     
     */
    public void setRows(Response.Rows value) {
        this.rows = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="row" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="dayorder" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="dayofweekstr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="starttime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="endtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="permit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="locationdesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="optionaltext" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="locationid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="start24" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="end24" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cnn" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="addr_date_create" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="addr_date_modified" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                   &lt;element name="lot" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="coldtruck" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="applicant" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                   &lt;element name="location_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="location_2_address" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="location_2_city" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="location_2_state" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="location_2_zip" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="_uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="_position" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *                 &lt;attribute name="_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class Rows {

        @XmlElement(required = true)
        protected List<Response.Rows.Row> row;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Response.Rows.Row }
         * 
         * 
         */
        public List<Response.Rows.Row> getRow() {
            if (row == null) {
                row = new ArrayList<Response.Rows.Row>();
            }
            return this.row;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="dayorder" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="dayofweekstr" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="starttime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="endtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="permit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="locationdesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="optionaltext" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="locationid" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="start24" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="end24" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cnn" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="addr_date_create" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="addr_date_modified" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="block" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *         &lt;element name="lot" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="coldtruck" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="applicant" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *         &lt;element name="location_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="location_2_address" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="location_2_city" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="location_2_state" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="location_2_zip" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *       &lt;attribute name="_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="_uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="_position" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
         *       &lt;attribute name="_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dayorder",
            "dayofweekstr",
            "starttime",
            "endtime",
            "permit",
            "location",
            "locationdesc",
            "optionaltext",
            "locationid",
            "start24",
            "end24",
            "cnn",
            "addrDateCreate",
            "addrDateModified",
            "block",
            "lot",
            "coldtruck",
            "applicant",
            "x",
            "y",
            "latitude",
            "longitude",
            "location2",
            "location2Address",
            "location2City",
            "location2State",
            "location2Zip"
        })
        public static class Row implements Comparable<Row>{

            @XmlSchemaType(name = "unsignedByte")
            protected short dayorder;
            @XmlElement(required = true)
            protected String dayofweekstr;
            @XmlElement(required = true)
            protected String starttime;
            @XmlElement(required = true)
            protected String endtime;
            @XmlElement(required = true)
            protected String permit;
            @XmlElement(required = true)
            protected String location;
            @XmlElement(required = true)
            protected String locationdesc;
            @XmlElement(required = true)
            protected String optionaltext;
            @XmlSchemaType(name = "unsignedInt")
            protected long locationid;
            @XmlElement(required = true)
            protected String start24;
            @XmlElement(required = true)
            protected String end24;
            @XmlSchemaType(name = "unsignedInt")
            protected long cnn;
            @XmlElement(name = "addr_date_create", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar addrDateCreate;
            @XmlElement(name = "addr_date_modified", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar addrDateModified;
            @XmlSchemaType(name = "unsignedShort")
            protected int block;
            @XmlSchemaType(name = "unsignedByte")
            protected short lot;
            @XmlElement(required = true)
            protected String coldtruck;
            @XmlElement(required = true)
            protected String applicant;
            @XmlElement(required = true)
            protected BigDecimal x;
            @XmlElement(required = true)
            protected BigDecimal y;
            @XmlElement(required = true)
            protected BigDecimal latitude;
            @XmlElement(required = true)
            protected BigDecimal longitude;
            @XmlElement(name = "location_2", required = true)
            protected String location2;
            @XmlElement(name = "location_2_address", required = true)
            protected Object location2Address;
            @XmlElement(name = "location_2_city", required = true)
            protected Object location2City;
            @XmlElement(name = "location_2_state", required = true)
            protected Object location2State;
            @XmlElement(name = "location_2_zip", required = true)
            protected Object location2Zip;
            @XmlAttribute(name = "_id", required = true)
            protected String id;
            @XmlAttribute(name = "_uuid", required = true)
            protected String uuid;
            @XmlAttribute(name = "_position", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short position;
            @XmlAttribute(name = "_address", required = true)
            protected String address;

            /**
             * Gets the value of the dayorder property.
             * 
             */
            public short getDayorder() {
                return dayorder;
            }

            /**
             * Sets the value of the dayorder property.
             * 
             */
            public void setDayorder(short value) {
                this.dayorder = value;
            }

            /**
             * Gets the value of the dayofweekstr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDayofweekstr() {
                return dayofweekstr;
            }

            /**
             * Sets the value of the dayofweekstr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDayofweekstr(String value) {
                this.dayofweekstr = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStarttime(String value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the endtime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndtime() {
                return endtime;
            }

            /**
             * Sets the value of the endtime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndtime(String value) {
                this.endtime = value;
            }

            /**
             * Gets the value of the permit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPermit() {
                return permit;
            }

            /**
             * Sets the value of the permit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPermit(String value) {
                this.permit = value;
            }

            /**
             * Gets the value of the location property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocation() {
                return location;
            }

            /**
             * Sets the value of the location property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocation(String value) {
                this.location = value;
            }

            /**
             * Gets the value of the locationdesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocationdesc() {
                return locationdesc;
            }

            /**
             * Sets the value of the locationdesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocationdesc(String value) {
                this.locationdesc = value;
            }

            /**
             * Gets the value of the optionaltext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOptionaltext() {
                return optionaltext;
            }

            /**
             * Sets the value of the optionaltext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOptionaltext(String value) {
                this.optionaltext = value;
            }

            /**
             * Gets the value of the locationid property.
             * 
             */
            public long getLocationid() {
                return locationid;
            }

            /**
             * Sets the value of the locationid property.
             * 
             */
            public void setLocationid(long value) {
                this.locationid = value;
            }

            /**
             * Gets the value of the start24 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStart24() {
                return start24;
            }

            /**
             * Sets the value of the start24 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStart24(String value) {
                this.start24 = value;
            }

            /**
             * Gets the value of the end24 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEnd24() {
                return end24;
            }

            /**
             * Sets the value of the end24 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnd24(String value) {
                this.end24 = value;
            }

            /**
             * Gets the value of the cnn property.
             * 
             */
            public long getCnn() {
                return cnn;
            }

            /**
             * Sets the value of the cnn property.
             * 
             */
            public void setCnn(long value) {
                this.cnn = value;
            }

            /**
             * Gets the value of the addrDateCreate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getAddrDateCreate() {
                return addrDateCreate;
            }

            /**
             * Sets the value of the addrDateCreate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setAddrDateCreate(XMLGregorianCalendar value) {
                this.addrDateCreate = value;
            }

            /**
             * Gets the value of the addrDateModified property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getAddrDateModified() {
                return addrDateModified;
            }

            /**
             * Sets the value of the addrDateModified property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setAddrDateModified(XMLGregorianCalendar value) {
                this.addrDateModified = value;
            }

            /**
             * Gets the value of the block property.
             * 
             */
            public int getBlock() {
                return block;
            }

            /**
             * Sets the value of the block property.
             * 
             */
            public void setBlock(int value) {
                this.block = value;
            }

            /**
             * Gets the value of the lot property.
             * 
             */
            public short getLot() {
                return lot;
            }

            /**
             * Sets the value of the lot property.
             * 
             */
            public void setLot(short value) {
                this.lot = value;
            }

            /**
             * Gets the value of the coldtruck property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColdtruck() {
                return coldtruck;
            }

            /**
             * Sets the value of the coldtruck property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColdtruck(String value) {
                this.coldtruck = value;
            }

            /**
             * Gets the value of the applicant property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApplicant() {
                return applicant;
            }

            /**
             * Sets the value of the applicant property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApplicant(String value) {
                this.applicant = value;
            }

            /**
             * Gets the value of the x property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getX() {
                return x;
            }

            /**
             * Sets the value of the x property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setX(BigDecimal value) {
                this.x = value;
            }

            /**
             * Gets the value of the y property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setY(BigDecimal value) {
                this.y = value;
            }

            /**
             * Gets the value of the latitude property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLatitude(BigDecimal value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setLongitude(BigDecimal value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the location2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocation2() {
                return location2;
            }

            /**
             * Sets the value of the location2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocation2(String value) {
                this.location2 = value;
            }

            /**
             * Gets the value of the location2Address property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getLocation2Address() {
                return location2Address;
            }

            /**
             * Sets the value of the location2Address property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setLocation2Address(Object value) {
                this.location2Address = value;
            }

            /**
             * Gets the value of the location2City property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getLocation2City() {
                return location2City;
            }

            /**
             * Sets the value of the location2City property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setLocation2City(Object value) {
                this.location2City = value;
            }

            /**
             * Gets the value of the location2State property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getLocation2State() {
                return location2State;
            }

            /**
             * Sets the value of the location2State property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setLocation2State(Object value) {
                this.location2State = value;
            }

            /**
             * Gets the value of the location2Zip property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getLocation2Zip() {
                return location2Zip;
            }

            /**
             * Sets the value of the location2Zip property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setLocation2Zip(Object value) {
                this.location2Zip = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the uuid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUuid() {
                return uuid;
            }

            /**
             * Sets the value of the uuid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUuid(String value) {
                this.uuid = value;
            }

            /**
             * Gets the value of the position property.
             * 
             */
            public short getPosition() {
                return position;
            }

            /**
             * Sets the value of the position property.
             * 
             */
            public void setPosition(short value) {
                this.position = value;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress(String value) {
                this.address = value;
            }
            
            @Override
            public String toString() {
                return "Food Truck [Apllicant=" + applicant + "]";
            }
         
            @Override
            public int compareTo(Row o) {
                return this.getApplicant().compareTo(o.getApplicant());
            }

        }

    }

}
